// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 // programmingSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  programmingSidebar: [
    {
      type: 'category',
      label: 'Programming Overview',
      link:{
        type:'generated-index',
            title: 'Overview',
            description: 'Add info here',
      },
      collapsed:false,
      items: [
        {
          type: 'category',
          label: 'Maple Sim/Advantage Kit',
          link:{
            type:'generated-index',
            title: 'Maple Sim and Advantage Kit',
            description: 'Add info here',
          },
          collapsed: true,
          items: ['programming-overview/AdvKitTemp', 'programming-overview/MapleSim'],
        },
        {
          type: 'category',
          label: 'Hardware Abstraction',
          link:{
            type:'generated-index',
            title: 'Hardware Abstraction',
            description: 'Add info here',
          },
          collapsed: true,
          items: ['programming-overview/IOReal','programming-overview/IOSim'],
        },
        {
          type: 'category',
          label: 'Configuring Motors',
          link:{
            type:'generated-index',
            title: 'Configuring Motors',
            description: 'Add info here',
          },
          collapsed: true,
          items: ['programming-overview/RevHardwareClient','programming-overview/PheonixTuner'],
        },
        {
          type: 'category',
          label: 'Control Loop Tuning',
          link:{
            type:'generated-index',
            title: 'Control Loop Tuning',
            description: 'Add info here',
          },
          collapsed: true,
          items: ['programming-overview/PID','programming-overview/FeedForward'],
        },
      ],
    },
  ],
   
};

export default sidebars;
